language: python
matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - env: TOXENV=flake8
install:
  - sudo apt-get install -y python-dev
  - sudo apt-get remove -y postgresql-9.2
  - sudo apt-get install -y postgresql-11
  - sudo apt-get install -y libpq-dev
  - pip install tox
script:
  - env PATH=/usr/lib/postgresql/11/bin:"$PATH" tox
